apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gav6jjnop-go 
  janus-idp.io/tekton: gav6jjnop-go
  backstage.io/kubernetes-id: gav6jjnop-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gav6jjnop-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml