apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gav6jjnop-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gav6jjnop-go 
  name: gav6jjnop-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gav6jjnop-go 
